### ISSUE TITLE
generate preload from runtime.json

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#273]
currently the preload job is "static" but since runtimes changes ofter the operator should actually build the preload job reading the versions from the runtime.json.

**Comment by msciabarra** [comment]
Hi this should be closed but some delays are reported so probably we should add a test to verify the preload matches the configured runtimes

**Comment by francescotimperi** [comment]
This is not the problem in my opinion. The preloader loads the runtime set a default reading from the configured runtimes.json configmap. The issue is that the operator executes it as a batch job and continue launching the rest of the component. For a minimal setup these are only couchdb and openwhisk standalone, and therefore it is possible that a request to execute an openwhisk action startes even before the preloader complete. One possibility to fix this it is to add a wait for condition=complete on the preloader batch job.
