### ISSUE TITLE
Check Docker and Java versions in the startup script

### ISSUE THREAD

**Issue by irinacodes** [nuvolaris/nuvolaris#44]
┆Issue is synchronized with this [Jira Task](https://nuvolaris.atlassian.net/browse/MVP-48) by [Unito](https://www.unito.io)

**Comment by irinacodes** [comment]
here https://github.com/nuvolaris/nuvolaris/blob/main/setup.source

**Comment by lpignotti** [comment]
Which docker and java versions must to be checked during the setup script running?
I mean, which are the min version can be accetable?

**Comment by msciabarra** [comment]
This is the startup script

https://github.com/nuvolaris/nuvolaris/blob/main/setup.source

The minimum java version is java 8
The minimum docker version is docker 18.03

currently the script just says ok if there IS java and docker

The problem does not happen with other languages like go, node etc because they are downloaded of the right version.

**Comment by pietroaragona** [comment]
Ok for docker, but seems that java is installed with the right version https://github.com/nuvolaris/nuvolaris/blob/main/Dockerfile#L43 
If so, we should check only docker version. Do you agree @msciabarra ?

**Comment by msciabarra** [comment]
The script can be executed also outside the Dockefile - check DEVEL.md that
explain how to run the development environment without the container. So it
have to check both dockerfile and java versions
