### ISSUE TITLE
Improve documentation for newcomers

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#45]
So far we found the following pain point that should be documented properly in the [developer guide](https://github.com/nuvolaris/nuvolaris/blob/main/docs/DEVEL.md)

* Under Linux Ubuntu you should NOT use docker.io but download a docker-ce of the right version
* Under Linux because of docker limitations you do better to develop with an UID of 1000 and never as root
* Explaning how to use properly gitmodules and how to contribute (i.e. create a new remote, NOT modifying .gitmodules)
* Note that you should NOT use clone with vscode for the top level project becuase it does not recurse subfolders
* In general distinguish working with a single subproject (that is the easy way) and how to work with the toplevel project that puts everthing together with submodules (the hard way)

┆Issue is synchronized with this [Jira Task](https://nuvolaris.atlassian.net/browse/MVP-49) by [Unito](https://www.unito.io)

**Comment by stoiclionroars** [comment]
Yesteday I did an attempt to setting up a development enviroment on a remote server (Ubuntu 20.04) using vscode as text editor.

Prerequisites:

- a remote server with a linux distro, a non-root user (uid=1000), docker ce installed by the non-root user;
- vscode with the extensions 'Remote - SSH' and 'Remote - Container' and a configuration enabling a connection to the romote server;
- a  fork of the parent project;

I'm a little uncomfortable to access the remote options with the f1 shortcut. Instead I use the left-bottom green button.
I clicked the green button, and then the option 'Clone Repository in container Volume' and all the other operations in order to
connect vscode with my github account.

All seemed to be well but at the end... It was weird that vscode doesn't open the folder of the child projects. I investigated a bit with a filesystem inspection (server terminal) and I discovered that only the parent project was forked and cloned while the child ones wasn't cloned and on my github account still referecing to the nuvolaris account.  The folder related to the child project had some kind file and vscode was able to open it only after i walking throught them  via command line on the server.

I expected that all the projects was forked and cloned, but this is not what github and vscode did.

In a previous local attempt i clone manually the project with the git clone statement, using the --recurse-submodules option. The result was that the whole project was cloned. In my last attempt I expected the same result.

**Comment by stoiclionroars** [comment]
Now I have two goals:
- Reproduce what exposed online on the whole project; i hope there's a way to do it on a remote server;
- Setting up a development eviroment for each child project where i can be helpful; maybe an indipendent enviroment for each one,
